# Generated by Django 5.0.4 on 2024-04-19 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='превью'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='published',
            field=models.BooleanField(blank=True, null=True, verbose_name='опубликовано'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='views',
            field=models.IntegerField(blank=True, null=True, verbose_name='просмотры'),
        ),
    ]
