# Generated by Django 5.0.4 on 2024-05-11 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_preview_alter_blog_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='превью'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='published',
            field=models.BooleanField(default='True', verbose_name='опубликовано'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='views',
            field=models.IntegerField(default='0', verbose_name='просмотры'),
        ),
    ]
