# Generated by Django 5.0.3 on 2024-04-03 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='название_категории')),
                ('description', models.TextField(blank=True, max_length=50, null=True, verbose_name='описание_категории')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.CreateModel(
            name='Prod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='наименование')),
                ('description', models.CharField(blank=True, max_length=50, null=True, verbose_name='описание')),
                ('preview', models.CharField(blank=True, max_length=50, null=True, verbose_name='превью')),
                ('cost', models.CharField(max_length=50, verbose_name='цена')),
                ('created_at', models.CharField(max_length=50, verbose_name='дата создания')),
                ('updated_at', models.CharField(max_length=50, verbose_name='дата последнего изменения')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.cat', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'продукты',
            },
        ),
    ]
