# Generated by Django 5.0.3 on 2024-04-04 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cat',
            new_name='Category',
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='наименование')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='описание')),
                ('preview', models.CharField(verbose_name='превью')),
                ('cost', models.IntegerField(verbose_name='цена')),
                ('created_at', models.CharField(verbose_name='дата создания')),
                ('updated_at', models.CharField(verbose_name='дата последнего изменения')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.category', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'продукты',
            },
        ),
        migrations.DeleteModel(
            name='Prod',
        ),
    ]
