# Generated by Django 5.0.4 on 2024-04-16 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_rename_cat_category_product_delete_prod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='превью'),
        ),
    ]
