# Generated by Django 5.0.4 on 2024-05-11 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_product_preview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='имя')),
                ('email', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='email')),
                ('password', models.CharField(max_length=50, verbose_name='пароль')),
                ('createable', models.BooleanField(default='False', verbose_name='возможность_создания')),
            ],
            options={
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'пользователи',
            },
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_num', models.CharField(max_length=50, unique=True, verbose_name='номер_версии')),
                ('version_name', models.CharField(max_length=50, verbose_name='имя_версии')),
                ('sign', models.BooleanField(max_length=50, verbose_name='признак_текущей_версии')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.product', verbose_name='продукт')),
            ],
            options={
                'verbose_name': 'версия',
                'verbose_name_plural': 'версии',
            },
        ),
    ]
