# Generated by Django 5.0.4 on 2024-05-19 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_product_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('change_published_status', 'Can change status "is_published"')], 'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
    ]
