# Generated by Django 5.0.4 on 2024-05-14 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, null=True, verbose_name='страна'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(verbose_name='пароль'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telephone_number',
            field=models.CharField(blank=True, null=True, verbose_name='телефон'),
        ),
    ]
